# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.runButton = QtWidgets.QPushButton(Form)
        self.runButton.setGeometry(QtCore.QRect(70, 120, 100, 40))
        self.runButton.setObjectName("runButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 230, 30, 30))
        self.label.setObjectName("label")
        self.CardEdit = QtWidgets.QLineEdit(Form)
        self.CardEdit.setGeometry(QtCore.QRect(60, 230, 240, 30))
        self.CardEdit.setObjectName("CardEdit")
        self.loginButton = QtWidgets.QPushButton(Form)
        self.loginButton.setGeometry(QtCore.QRect(310, 230, 75, 30))
        self.loginButton.setObjectName("loginButton")
        self.stopButton = QtWidgets.QPushButton(Form)
        self.stopButton.setGeometry(QtCore.QRect(250, 120, 100, 40))
        self.stopButton.setObjectName("stopButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 30, 54, 30))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 70, 54, 30))
        self.label_3.setObjectName("label_3")
        self.daoqilabel = QtWidgets.QLabel(Form)
        self.daoqilabel.setGeometry(QtCore.QRect(170, 30, 141, 30))
        self.daoqilabel.setObjectName("daoqilabel")
        self.yxsjlabel = QtWidgets.QLabel(Form)
        self.yxsjlabel.setGeometry(QtCore.QRect(170, 70, 141, 30))
        self.yxsjlabel.setObjectName("yxsjlabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Auto_Apex"))
        self.runButton.setText(_translate("Form", "开始"))
        self.label.setText(_translate("Form", "卡密："))
        self.loginButton.setText(_translate("Form", "登录"))
        self.stopButton.setText(_translate("Form", "停止"))
        self.label_2.setText(_translate("Form", "到期时间："))
        self.label_3.setText(_translate("Form", "运行时间："))
        self.daoqilabel.setText(_translate("Form", "0"))
        self.yxsjlabel.setText(_translate("Form", "0"))
